name: "NTFY"
description: "NTFY notification server addon"
version: "0.0.1"
slug: "ntfy"
url: "https://github.com/Farmer-Eds-Shed/Home-Assistant-Addon-Repo"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  80/tcp: 8000
