name: "Ruuvi"
description: "Ruuvi Go Gateway addon"
version: "0.0.3"
slug: "ruuvi"
url: "https://github.com/Farmer-Eds-Shed/Home-Assistant-Addon-Repo"
init: false
host_network: true
host_dbus: true
uart: true
privileged: 
  - NET_ADMIN
devices:
  - /dev/ttyAMA0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  gw_mac: "AB:AB:00:00:00:20"
  broker_url: "tcp://172.17.0.1:1883"
  user_name: ""
  password: ""
schema:
  gw_mac: str
  broker_url: str
  user_name: str
  password: password
startup: services
