name: "Ruuvi"
description: "Ruuvi Go Gateway addon"
version: "0.0.1"
slug: "ruuvi"
init: false
host_network: true
host_dbus: true
uart: true
privileged: 
  - NET_ADMIN
devices:
  - /dev/ttyAMA0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  gw_mac: "AB:AB:00:00:00:20"
  broker_url: ""
  user_name: ""
  password: ""
schema:
  gw_mac: str
  broker_url: str
  user_name: str
  password: password
startup: services